trigger:
- main

# (opcional) pode remover toda a seção resources; se quiser manter, corrija o typo:
resources:
- repo: self

variables:
  # vmImage não será usado com self-hosted, pode até remover
  vmImageName: 'ubuntu-latest'

  dockerRegistryServiceConnection: '36a8a371-f371-4897-bbf2-799a200c1621'
  containerRegistry: 'produto.azurecr.io'

  apiImageRepository: 'produtos-api'
  webImageRepository: 'produtos-web'

  buildTag: '$(Build.BuildId)'
  latestTag: 'latest'

stages:
- stage: BuildAndPush
  displayName: Build & Push API + WEB
  jobs:

  - job: API
    displayName: Build & Push API
    pool: 
      name: Default           # << usa seu pool self-hosted (agente online)
    steps:
    - task: Docker@2
      displayName: Build & Push API image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(apiImageRepository)
        dockerfile: 'produtos.api/Dockerfile'   # confira o Case/caminho
        buildContext: 'produtos.api'            # confira o Case/caminho
        tags: |
          $(buildTag)
          $(latestTag)

  - job: WEB
    displayName: Build & Push WEB
    pool: 
      name: Default           # << mesmo pool
    steps:
    - task: Docker@2
      displayName: Build & Push WEB image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(webImageRepository)
        dockerfile: 'web/Dockerfile'
        buildContext: 'web'
        # Se precisar passar --build-arg (Vite), separe em build + push (ver nota abaixo)
        tags: |
          $(buildTag)
          $(latestTag)
